name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: react-ros2

    - name: Run development server
      run: npm run dev &
      working-directory: react-ros2

    - name: Wait for server to start
      run: sleep 10

    - name: Stop development server
      run: pkill -f "npm run dev"
      working-directory: react-ros2

    - name: Cleanup
      run: |
        echo "Cleaning up..."
        rm -rf node_modules
      working-directory: react-ros2